// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int i = 0;
		int k = 0;
		int j = 0;
	while(i<N) {
		double a= Math.random();
		if(a>=0.5) {
			k ++;
		}
		else if(a<0.5) {
			j ++;
		}
	i ++;
	}
System.out.println("> 0.5:  "+ j+ " times" );
System.out.println("<= 0.5: "+ k + " times");


	}
}
